# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    view:
        view_response_listener:  true
    format_listener:
        enabled: true
        rules:
            - { path: '^/api', priorities: [ 'json', 'xml' ], fallback_format: json, attributes: { _controller: FOS\RestBundle\Controller\ExceptionController }, prefer_extension: false }
            # setting a priority to */* basically means any format will be matched
            - { path: '^/', priorities: [ 'text/html', '*/*' ], fallback_format: html, prefer_extension: true }
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
